version: '2'
services:
  jenkins:
    image: 'jenkins_juliherms:latest'
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock